name: Docker Image CI

on:
  push:
    branches:
    - release
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
    - name: Making ENV file
      run: 
        touch .env
        echo TOKEN=${{ secrets.TOKEN }} >> .env
        echo GUILD=${{ secrets.GUILD }} >> .env
        echo CLIENT=${{ secrets.CLIENT }} >> .env
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag $(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]'):latest;
        ls -la
