name: Docker Image CI

on:
  push:
    branches:
    - release
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
    - name: Making ENV file
      run: 
        touch .env
        echo TOKEN=${{ secrets.TOKEN }} >> .env
        echo GUILD=${{ secrets.GUILD }} >> .env
        echo CLIENT=${{ secrets.CLIENT }} >> .env
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Publish
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: $(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]'):latest
