name: Docker Image CI

on:
  push:
    branches:
    - release
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
    - name: Making ENV file
      uses: vafinvr/template-env-action@master
      env:
        TOKEN: ${{ secrets.TOKEN }}
        GUILD: ${{ secrets.GUILD }}
        CLIENT: ${{ secrets.CLIENT }}
      with:
        filename: '.env.example'
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${GITHUB_REPOSITORY#*/}:latest
