name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: a2m1/slim-ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          key: ${{ secrets.KEY }}
          script: 
            ls /home/ubuntu/
            
