name: Deploy

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USER }}
            PORT: 22
            KEY: ${{ secrets.KEY }}
            script: ls
