name: Deploy
on: 
  push:
    branches: 
      -main
  workflow_dispatch:

jobs:
  deply:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: 'placeholder'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzn ./ ubuntu@${{ secrets.SSH_HOST }}:/home/ubuntu/Clandestine
