name: Deploy

on: [push]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          
          - name: Transfer Repository Content
            uses: appleboy/scp-action@master
            with:
                HOST: ${{ secrets.HOST }}
                USERNAME: ${{ secrets.USER }}
                PORT: ${{ secrets.PORT }}
                KEY: ${{ secrets.KEY }}
                source: "*"
                target: "/home/ubuntu/Clandestine"
                rm: true
                
          - name: Deploy App
            uses: appleboy/ssh-action@master
            with:
                HOST: ${{ secrets.HOST }}
                USERNAME: ${{ secrets.USER }}
                PORT: ${{ secrets.PORT }}
                KEY: ${{ secrets.KEY }}
                script: |
                    cd /home/ubuntu/Clandestine
                    rm .env.example .git* LICENSE README.md
                    echo -e 'TOKEN=${{ secrets.CLIENT }}\nGUILD=${{ secrets.CLIENT }}\nClient=${{ secrets.CLIENT }}' >> .env
                    sudo rm -rf node_modules package-lock.json
                    sudo npm install
                    sudo pm2 kill
                    sudo pm2 start clandestine.js --name Clandestine
